# SPDX-License-Identifier: MIT
---
- name: Example trustee_attestation_server role invocation
  hosts: all
  vars:
    trustee_attestation_server_foo: example variable value
    trustee_attestation_server_bar: false
  roles:
    - linux-system-roles.trustee_attestation_server
